openapi: 3.0.0
info:
  title: Twilio Reminder App
  description: >-
    This is an app designed to send, get, and drop reminders from a database, as
    well as send notifications for any expired reminders via the Twilio app.
  version: 0.1.0
paths:
  /get:
    get:
      summary: Retrieves a list of reminders in the database
      description: >-
        Allows the user to request a list of the reminders in the database using
        the command line interface.

        The return type is a JSON array of reminder objects, or an empty list if
        zero reminders exist.
      responses:
        '200':
          description: >-
            A JSON array of reminder objects, represented as dicts of time
            (datetime), message (string), and unique ID (int).
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                    description: Time of reminder.
                  message:
                    type: string
                    description: Message given at appropriate time.
                  id:
                    type: integer
                    description: Unique identifying id for reminder.
        '404':
          description: Used in case the database does not exist.
